import jwt

token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4MTIwMDgyLCJpYXQiOjE3NjgxMTY0ODIsImp0aSI6ImE3YzlmZDQxYjcyNTQ2M2FiMDJkOTU5MGZiYzcyNGZlIiwidXNlcl9pZCI6IjA1ZjU5YzY3LTVhNzQtNGRlOS1iNGJhLTFjNDY1NTRiZWNkNSIsInVzZXJuYW1lIjoidXNlciIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSJ9.fJNkpCRKHtEsWRIyHpXrrYHSxgHVbBulvMzI45nJbbJ-zz-luoqtBaq4vHstOTjmZ8Zunu6zCp35lSRSJEJCkanc3ozZt2KRYGNWXIMYKxlkOjU_aZbveFOmLSN9Q8p2H2FF3Il8SQxWy_ByylbsIA9V-BVMfMOMxGJ18rfTPe5MbC257nQehn_JZsorGxitI3vypVDaaiaXygBxWUFNZ7og8tuDQA5mYyL4n7bGK5jD_iAN34WxlBgkFnHmtNafzgVz8nsl_O14XpbKKz6lmNqP4e4xGlX3Rm5p4Kh5WCnTUzIDzcr--UNWXeB_GNplOHFB2hkR0Rt_-tzemeeuXw"
# decode without verifying signature
payload = jwt.decode(token, options={"verify_signature": False})
print(payload)