"""Add sprint_id to tasks

Revision ID: 2e708cbaeb61
Revises: 4f060f875347
Create Date: 2026-02-01 08:39:52.123685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e708cbaeb61'
down_revision: Union[str, Sequence[str], None] = '4f060f875347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('sprint_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'sprint_id')
    # ### end Alembic commands ###
